volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    container_name: backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    container_name: frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static


  nginx:
    build: ./infra/
    container_name: nginx
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media
