
volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vvarra/foodgram-backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: vvarra/foodgram-frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static


  nginx:
    image: vvarra/foodgram-gateway:latest
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
