# Generated by Django 3.2.3 on 2024-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20241121_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='cookbook.Tag', verbose_name='Теги'),
        ),
    ]
