# Generated by Django 3.2.3 on 2024-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20241130_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=None, max_length=6, null=True, verbose_name='Короткая ссылка'),
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
