# Generated by Django 3.2.3 on 2024-11-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0006_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('id',), 'verbose_name': 'Короткая ссылка на рецепт', 'verbose_name_plural': 'Короткие ссылки на рецепты'},
        ),
        migrations.AlterUniqueTogether(
            name='shortlink',
            unique_together={('recipe', 'short_link')},
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe', verbose_name='Рецепты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ('id',),
                'unique_together': {('user', 'recipes')},
            },
        ),
    ]
