# Generated by Django 3.2.3 on 2024-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20241125_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(to='cookbook.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipes',
        ),
    ]
