# Generated by Django 3.2.3 on 2024-11-21 11:08

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241120_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, upload_to=users.utils.avatar_upload_path),
        ),
    ]
