# Generated by Django 3.2.3 on 2024-11-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
