# Generated by Django 3.2.3 on 2024-11-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',)},
        ),
    ]
